### ISSUE TITLE
When you follow a link to a "section" of a file, the Colab navigation bar blocks the first couple of lines.

### ISSUE THREAD

**Issue by Kenneth-T-Moore** [OpenMDAO/OpenMDAO_Book#132]
Not sure how to resolve this, but if you follow a link to a section of a document, you can't see the section header because it is covered by the Colab navigation bar. It is very disorienting, and I think it will confuse users.

**Comment by DKilkenny** [comment]
Closing issue because this is a jupyterbook issue. Submitted issue to their Github and will update if fix is made
